### PR TITLE
Create info page - Related #126

### PR DESCRIPTION
**Pull request by RhodesPeter**
This relates to an comment by Jasmin on issue #126.

- add /info page and route
- add tests for /info route
- add info-icon-white.svg and info-icon-black.svg to assets
- add info icon to finished page

### CODE REVIEW

**Comment by des-des** [comment]
@RhodesPeter @skibinska emoji-happy / sad / indifferent are also 1MB each

**Comment by RhodesPeter** [comment]
Thanks @des-des 😀

- emojis are now no more than 12kb
- icons are now around 825 bytes

**Comment by RhodesPeter** [comment]
Test are failing so I am unassigning Eoin.

**Comment by des-des** [comment]
image

**Comment by RhodesPeter** [comment]
When PR #147 or #146 are merged into master I believe codecov will not be failing.

**Pull request merged**
